#try to change it from you outputPath "dist/angular-app",
version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    working_directory: ~/angular-app  #try to change it from you outputPath "dist/angular-app"
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-app-{{ .Branch }}-{{ checksum "package-lock.json"}}
      - run: npm install
      - save_cache:
          key: angular-app-{{ .Branch }}-{{ checksum "package-lock.json"}}
          paths:
            - "nodes_modules"
      #- run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run build
      - deploy:
          command: |  #try to change it from you outputPath "dist/angular-app",
            ./node_modules/.bin/surge --project ~/angular-app/dist/angular-app --domain safouene.surge.sh
workflows:
    build-and-test:
      jobs:
        - build-and-test
